version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: coinflip_game-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=coinflip_game
    networks:
      - app_network


  backend:
    build:
      context: ./backend
    container_name: coinflip_game-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/coinflip_game
      - DOCKER=true
    depends_on:
      - mongodb
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: coinflip_game-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: coinflip_game-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
  jenkins_home: