version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/coinflip_game"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"